---
controller_credentials:
  - name: "AWX-Machine Credential"
    description: ""
    credential_type: "Machine"
    organization: "AWX-ORG"
    inputs:
      password: "{{ vaulted_machine_password }}"
      username: "{{ vaulted_machine_username }}"

...
